export type Printer = {
  id: string;
  name: string;
  brand: "Ultimaker" | "Formlabs" | "Bambu Lab" | "Creality" | "Desktop Metal" | "Intamsys" | "BigRep" | "Elegoo";
  slug: string;
  description: string;
  price: string;
  images: string[];
  specs: {
    buildVolume?: string;
    resolution?: string;
    materials?: string;
    connectivity?: string;
    printSpeed?: string;
    nozzleTemp?: string;
    bedTemp?: string;
  };
  features?: string[];
};

// New images path - all properly named PNGs
const IMG = "/products/printers/new";

export const printers: Printer[] = [
  // ==================== ULTIMAKER ====================
  {
    id: "ultimaker-makerbot-sketch-sprint",
    name: "Ultimaker MakerBot Sketch Sprint",
    brand: "Ultimaker",
    slug: "ultimaker-makerbot-sketch-sprint",
    description: "The MakerBot Sketch Sprint is a fast, reliable 3D printer purpose-built for education. Featuring an enclosed build chamber with HEPA filtration for safe classroom use, it delivers consistent results with minimal setup. Cloud-enabled classroom management allows teachers to monitor and control multiple printers remotely, making it ideal for STEM curricula and design thinking programs.",
    price: "R41 999",
    images: [`${IMG}/Ultimaker-MakerBot-Sketch-Sprint.png`],
    specs: {
      buildVolume: "200 x 200 x 220 mm",
      resolution: "100 - 400 micron",
      materials: "PLA, Tough PLA, MakerBot Precision PLA",
      connectivity: "Wi-Fi (2.4GHz/5GHz), Ethernet, USB",
      printSpeed: "Up to 150 mm/s",
      nozzleTemp: "Up to 215°C",
      bedTemp: "Up to 60°C (heated build plate)",
    },
    features: [
      "HEPA + activated carbon air filtration",
      "Fully enclosed build chamber",
      "MakerBot CloudPrint integration",
      "Classroom management dashboard",
      "Automatic filament detection",
      "On-device camera for remote monitoring",
      "Flexible spring steel build plate",
      "Quiet operation (<50dB)",
    ],
  },
  {
    id: "ultimaker-s5",
    name: "Ultimaker S5",
    brand: "Ultimaker",
    slug: "ultimaker-s5",
    description: "The Ultimaker S5 is a large-format dual extrusion 3D printer engineered for professional environments. With its generous 330 x 240 x 300 mm build volume, it handles complex multi-material prints with ease. The swappable print core system enables quick material changes, while active bed leveling ensures perfect first layers every time. Ideal for functional prototypes, manufacturing aids, and end-use parts.",
    price: "R168 999",
    images: [`${IMG}/Ultimaker-S5.png`],
    specs: {
      buildVolume: "330 x 240 x 300 mm",
      resolution: "20 - 600 micron (layer height)",
      materials: "PLA, ABS, Nylon, TPU 95A, PVA, PP, CPE, CPE+, PC, Breakaway",
      connectivity: "Wi-Fi (2.4GHz/5GHz), Ethernet, USB",
      printSpeed: "Up to 300 mm/s",
      nozzleTemp: "Up to 280°C",
      bedTemp: "Up to 140°C (heated glass build plate)",
    },
    features: [
      "Dual extrusion with water-soluble supports",
      "Active bed leveling with capacitive sensor",
      "Filament flow sensor for jam detection",
      "Swappable print core system (AA/BB/CC)",
      "4.7\" touchscreen interface",
      "NFC material recognition",
      "Enclosed front with glass doors",
      "Cura software integration",
      "Remote monitoring via Ultimaker Digital Factory",
    ],
  },
  {
    id: "ultimaker-s5-pro-bundle",
    name: "Ultimaker S5 Pro Bundle",
    brand: "Ultimaker",
    slug: "ultimaker-s5-pro-bundle",
    description: "The Ultimaker S5 Pro Bundle is the complete professional 3D printing solution, combining the S5 printer with the Material Station and Air Manager. The Material Station provides automated filament handling with humidity control for up to 6 spools, enabling unattended 24/7 production. The Air Manager creates a closed airflow system with an EPA filter for safe indoor operation with engineering materials.",
    price: "R266 197",
    images: [`${IMG}/Ultimaker-S5-Pro-Bundle.png`],
    specs: {
      buildVolume: "330 x 240 x 300 mm",
      resolution: "20 - 600 micron (layer height)",
      materials: "PLA, ABS, Nylon, TPU 95A, PVA, PP, CPE, CPE+, PC, Breakaway, Composite materials",
      connectivity: "Wi-Fi (2.4GHz/5GHz), Ethernet, USB",
      printSpeed: "Up to 300 mm/s",
      nozzleTemp: "Up to 280°C",
      bedTemp: "Up to 140°C (heated glass build plate)",
    },
    features: [
      "Material Station with 6-spool capacity",
      "Air Manager with EPA filtration",
      "Humidity-controlled material storage (<40% RH)",
      "Automated material switching",
      "24/7 unattended production capability",
      "Composite-ready print cores available",
      "Inside-out airflow for safe operation",
      "Ultimaker Digital Factory integration",
      "Enterprise-grade reliability",
    ],
  },
  {
    id: "ultimaker-s6",
    name: "Ultimaker S6",
    brand: "Ultimaker",
    slug: "ultimaker-s6",
    description: "The Ultimaker S6 builds on the proven S-series platform with enhanced reliability features and improved print quality. Designed for professional environments requiring consistent, high-quality output, it features dual extrusion for complex geometries with soluble supports, active bed leveling for perfect adhesion, and the proven print core system for versatile material compatibility.",
    price: "R149 999",
    images: [`${IMG}/Ultimaker-S6.png`],
    specs: {
      buildVolume: "330 x 240 x 300 mm",
      resolution: "20 - 600 micron (layer height)",
      materials: "PLA, ABS, Nylon, TPU 95A, PVA, PP, CPE, Breakaway",
      connectivity: "Wi-Fi (2.4GHz/5GHz), Ethernet, USB",
      printSpeed: "Up to 300 mm/s",
      nozzleTemp: "Up to 280°C",
      bedTemp: "Up to 140°C",
    },
    features: [
      "Dual extrusion system",
      "Active bed leveling with inductive sensor",
      "Enhanced motion system reliability",
      "Swappable print core system",
      "4.7\" color touchscreen",
      "NFC filament recognition",
      "Cura slicing software",
      "Remote print management",
    ],
  },
  {
    id: "ultimaker-s7",
    name: "Ultimaker S7",
    brand: "Ultimaker",
    slug: "ultimaker-s7",
    description: "The Ultimaker S7 represents the next generation of professional desktop 3D printing. Featuring an integrated Air Manager for safe indoor operation, a flexible PEI-coated build plate for easy part removal, and enhanced auto bed leveling with 121-point probing. The higher temperature hot end (340°C) enables printing with advanced engineering materials including polycarbonate and high-performance composites.",
    price: "R219 999",
    images: [`${IMG}/UltiMaker-S7_01-No-Background.png`],
    specs: {
      buildVolume: "330 x 240 x 300 mm",
      resolution: "6.9 - 600 micron (ultra-fine to draft)",
      materials: "PLA, ABS, Nylon, TPU 95A, PVA, PP, PC, CPE+, Composites",
      connectivity: "Wi-Fi (2.4GHz/5GHz), Ethernet, USB",
      printSpeed: "Up to 300 mm/s",
      nozzleTemp: "Up to 340°C (high-temp print core)",
      bedTemp: "Up to 140°C (heated flex plate)",
    },
    features: [
      "Integrated Air Manager with EPA filter",
      "Flexible PEI-coated build plate",
      "121-point auto bed leveling",
      "High-temperature print core (340°C)",
      "Material Station compatible",
      "5\" full-color touchscreen",
      "Dual extrusion with soluble supports",
      "Ultimaker Digital Factory cloud platform",
      "Advanced material profiles in Cura",
    ],
  },
  {
    id: "ultimaker-s7-pro-bundle",
    name: "Ultimaker S7 Pro Bundle",
    brand: "Ultimaker",
    slug: "ultimaker-s7-pro-bundle",
    description: "The ultimate professional 3D printing ecosystem combining the Ultimaker S7 with Material Station and integrated Air Manager. This complete solution delivers unattended 24/7 production capability with automated material handling, humidity-controlled storage, and safe indoor operation. Perfect for design studios, engineering departments, and production environments requiring maximum uptime and material versatility.",
    price: "R302 998",
    images: [`${IMG}/UltiMaker-S7-pro-bundle_01-No-background.png`],
    specs: {
      buildVolume: "330 x 240 x 300 mm",
      resolution: "6.9 - 600 micron (ultra-fine to draft)",
      materials: "PLA, ABS, Nylon, TPU 95A, PVA, PP, PC, CPE+, Composites, Engineering grades",
      connectivity: "Wi-Fi (2.4GHz/5GHz), Ethernet, USB",
      printSpeed: "Up to 300 mm/s",
      nozzleTemp: "Up to 340°C (high-temp print core)",
      bedTemp: "Up to 140°C (heated flex plate)",
    },
    features: [
      "Material Station with 6-spool capacity",
      "Integrated Air Manager with EPA filter",
      "Humidity-controlled storage (<40% RH)",
      "Flexible PEI-coated build plate",
      "121-point auto bed leveling",
      "24/7 unattended production",
      "High-temperature capability (340°C)",
      "Ultimaker Digital Factory cloud platform",
      "Enterprise-grade reliability and support",
    ],
  },
  {
    id: "ultimaker-s8",
    name: "Ultimaker S8",
    brand: "Ultimaker",
    slug: "ultimaker-s8",
    description: "The Ultimaker S8 is the latest evolution of the S-series platform, delivering enhanced speed, reliability, and material capabilities for demanding professional applications. With improved motion systems enabling faster print speeds up to 350 mm/s, next-generation print cores, and advanced material compatibility, it sets a new standard for desktop professional 3D printing.",
    price: "R249 000",
    images: [`${IMG}/Ultimaker-S8.png`],
    specs: {
      buildVolume: "330 x 240 x 300 mm",
      resolution: "6.9 - 600 micron (ultra-fine to draft)",
      materials: "PLA, ABS, Nylon, TPU 95A, PVA, PP, PC, CPE+, Composites",
      connectivity: "Wi-Fi (2.4GHz/5GHz), Ethernet, USB",
      printSpeed: "Up to 350 mm/s (enhanced motion)",
      nozzleTemp: "Up to 340°C",
      bedTemp: "Up to 140°C",
    },
    features: [
      "Next-generation print core technology",
      "Enhanced motion system (350 mm/s)",
      "Improved reliability and uptime",
      "Advanced material compatibility",
      "Ultimaker Digital Factory integration",
      "5\" touchscreen interface",
      "Dual extrusion with soluble supports",
      "Air Manager compatible",
      "Material Station compatible",
    ],
  },
  {
    id: "ultimaker-factor-4",
    name: "UltiMaker Factor 4",
    brand: "Ultimaker",
    slug: "ultimaker-factor-4",
    description: "The UltiMaker Factor 4 is an industrial-grade FDM 3D printer engineered for high-performance engineering materials. With a heated chamber up to 70°C and hot end temperatures reaching 420°C, it processes demanding materials like PEEK, PEKK, ULTEM, and carbon fiber composites. Built for production environments with enterprise-grade security, traceability, and reliability.",
    price: "R499 999",
    images: [`${IMG}/UltiMaker-Factor-4.png`],
    specs: {
      buildVolume: "330 x 240 x 300 mm",
      resolution: "50 - 600 micron (layer height)",
      materials: "PEEK, PEKK, ULTEM 9085, PEI, Carbon Fiber Nylon, Glass Fiber Nylon",
      connectivity: "Wi-Fi (2.4GHz/5GHz), Ethernet, USB",
      printSpeed: "Up to 300 mm/s",
      nozzleTemp: "Up to 420°C (high-performance hot end)",
      bedTemp: "Up to 160°C (heated chamber up to 70°C)",
    },
    features: [
      "Heated chamber up to 70°C",
      "420°C high-performance hot end",
      "Industrial-grade materials (PEEK, ULTEM)",
      "Enterprise security and traceability",
      "Production-ready reliability",
      "Hardened steel nozzle included",
      "Advanced thermal management",
      "Ultimaker Digital Factory integration",
      "ISO 13485 compatible workflow",
    ],
  },
  {
    id: "ultimaker-factor-4-stand",
    name: "UltiMaker Factor 4 with Stand",
    brand: "Ultimaker",
    slug: "ultimaker-factor-4-stand",
    description: "The complete UltiMaker Factor 4 package with dedicated professional stand for optimal workspace ergonomics. This industrial-grade solution provides everything needed for high-performance material processing in production environments. The stand offers stable operation, cable management, and convenient storage for accessories and materials.",
    price: "R539 999",
    images: [`${IMG}/UltiMaker-Factor-4-with-Stand.png`],
    specs: {
      buildVolume: "330 x 240 x 300 mm",
      resolution: "50 - 600 micron (layer height)",
      materials: "PEEK, PEKK, ULTEM 9085, PEI, Carbon Fiber Nylon, Glass Fiber Nylon",
      connectivity: "Wi-Fi (2.4GHz/5GHz), Ethernet, USB",
      printSpeed: "Up to 300 mm/s",
      nozzleTemp: "Up to 420°C (high-performance hot end)",
      bedTemp: "Up to 160°C (heated chamber up to 70°C)",
    },
    features: [
      "Professional stand with storage",
      "Heated chamber up to 70°C",
      "420°C high-performance hot end",
      "Industrial-grade materials (PEEK, ULTEM)",
      "Ergonomic working height",
      "Integrated cable management",
      "Enterprise security and traceability",
      "Production-ready reliability",
      "Ultimaker Digital Factory integration",
    ],
  },
  {
    id: "ultimaker-pva-removal-station",
    name: "Ultimaker PVA Removal Station",
    brand: "Ultimaker",
    slug: "ultimaker-pva-removal-station",
    description: "The Ultimaker PVA Removal Station automates the dissolution of water-soluble PVA support material, streamlining your post-processing workflow. With temperature-controlled water circulation and a basket system that fits S5/S7 build plates, it delivers consistent, hands-free support removal in hours rather than days.",
    price: "R13 070",
    images: [`${IMG}/Ultimaker-PVA-Removal-Station.png`],
    specs: {
      buildVolume: "Fits S5/S7 build plates (330 x 240 mm)",
      materials: "PVA water-soluble support material",
      connectivity: "Standalone operation",
    },
    features: [
      "Automated PVA dissolution",
      "Temperature-controlled water bath",
      "Circulation pump for faster removal",
      "Hands-free operation",
      "S5/S7 build plate compatible",
      "Removable basket system",
      "Timer-controlled cycles",
      "Reduces post-processing time significantly",
    ],
  },

  // ==================== FORMLABS ====================
  {
    id: "formlabs-form-4",
    name: "Form 4",
    brand: "Formlabs",
    slug: "formlabs-form-4",
    description: "The Form 4 is Formlabs' next-generation MSLA 3D printer, delivering up to 2x faster print speeds than previous generations while maintaining exceptional 25-micron accuracy. The Low Force Display (LFD) technology ensures gentle peel forces for reliable printing of intricate details. With an automated resin dispensing system and intuitive touchscreen interface, it's designed for professional workflows in engineering, design, and manufacturing.",
    price: "R91 743",
    images: [`${IMG}/Form-4.png`],
    specs: {
      buildVolume: "200 x 125 x 210 mm (5.2L)",
      resolution: "25 micron XY, 25-300 micron Z (layer height)",
      materials: "Standard, Tough, Durable, Flexible, High Temp, Castable, Engineering resins",
      connectivity: "Wi-Fi (2.4GHz/5GHz), Ethernet, USB",
      printSpeed: "Up to 2x faster than Form 3+",
    },
    features: [
      "Low Force Display (LFD) MSLA technology",
      "25 micron XY resolution",
      "Automated resin dispensing",
      "5.5\" touchscreen interface",
      "Light Processing Unit (LPU)",
      "Resin cartridge system (automatic fill)",
      "PreForm software with auto-orientation",
      "Remote print monitoring via Dashboard",
      "Quick Release Tank system",
    ],
  },
  {
    id: "formlabs-form-4b",
    name: "Form 4B",
    brand: "Formlabs",
    slug: "formlabs-form-4b",
    description: "The Form 4B is purpose-built for dental and medical applications, featuring the same blazing-fast MSLA technology as the Form 4 with validated biocompatible materials. Designed for dental labs, clinics, and medical device manufacturers, it produces surgical guides, dental models, splints, and custom medical devices with regulatory-compliant workflows.",
    price: "R135 913",
    images: [`${IMG}/Form-4B.png`],
    specs: {
      buildVolume: "200 x 125 x 210 mm (5.2L)",
      resolution: "25 micron XY, 25-300 micron Z (layer height)",
      materials: "Dental LT Clear, Surgical Guide, IBT Flex, Dental Model, Biocompatible resins",
      connectivity: "Wi-Fi (2.4GHz/5GHz), Ethernet, USB",
      printSpeed: "Up to 2x faster than Form 3B+",
    },
    features: [
      "Validated biocompatible materials",
      "FDA 510(k) cleared resins available",
      "Dental and medical workflow optimized",
      "Class I and Class II medical devices",
      "Surgical guide production",
      "Dental model and splint printing",
      "ISO 13485 compatible workflow",
      "Formlabs Dental Service Plan available",
      "PreForm software with dental presets",
    ],
  },
  {
    id: "formlabs-form-4l",
    name: "Form 4L",
    brand: "Formlabs",
    slug: "formlabs-form-4l",
    description: "The Form 4L brings large-format MSLA printing to professional environments with a 335 x 200 x 300 mm build volume—over 5x larger than the Form 4. Ideal for prototyping large parts, batch production, and manufacturing aids, it delivers the same exceptional accuracy and speed as the Form 4 at a significantly larger scale.",
    price: "R257 290",
    images: [`${IMG}/Form-4L.png`],
    specs: {
      buildVolume: "335 x 200 x 300 mm (20.1L)",
      resolution: "25 micron XY, 25-300 micron Z (layer height)",
      materials: "Standard, Tough, Durable, Flexible, High Temp, Engineering resins",
      connectivity: "Wi-Fi (2.4GHz/5GHz), Ethernet, USB",
      printSpeed: "Fast large-format printing",
    },
    features: [
      "5x larger build volume than Form 4",
      "Low Force Display (LFD) technology",
      "Large-scale prototyping",
      "Batch production capability",
      "Manufacturing aids and fixtures",
      "Automated resin system",
      "7\" touchscreen interface",
      "Form 4L Build Platform",
      "Compatible with Form Wash L and Cure L",
    ],
  },
  {
    id: "formlabs-form-3b-plus",
    name: "Form 3B+",
    brand: "Formlabs",
    slug: "formlabs-form-3b-plus",
    description: "The Form 3B+ is a professional-grade dental and medical 3D printer utilizing Low Force Stereolithography (LFS) technology. Optimized for biocompatible materials, it produces surgical guides, dental models, orthodontic appliances, and custom medical devices with exceptional accuracy and surface finish. Validated workflows ensure regulatory compliance for clinical applications.",
    price: "R108 366",
    images: [`${IMG}/Form-3B+.png`],
    specs: {
      buildVolume: "145 x 145 x 185 mm (3.9L)",
      resolution: "25 micron XY, 25-300 micron Z",
      materials: "Dental LT Clear, Surgical Guide, Dental Model, IBT Flex, Biocompatible resins",
      connectivity: "Wi-Fi (2.4GHz/5GHz), Ethernet, USB",
    },
    features: [
      "Low Force Stereolithography (LFS)",
      "Validated biocompatible materials",
      "Dental and orthodontic applications",
      "Surgical guide production",
      "FDA 510(k) cleared resins",
      "Clinical-ready workflow",
      "Light Touch Supports",
      "Formlabs Dental Service Plan",
      "PreForm dental presets",
    ],
  },
  {
    id: "formlabs-form-auto",
    name: "Form Auto",
    brand: "Formlabs",
    slug: "formlabs-form-auto",
    description: "Form Auto transforms your Form 3+ or Form 3B+ into an automated production system capable of 24/7 unattended operation. The robotic arm automatically removes completed prints and queues the next job, dramatically increasing throughput without manual intervention. Integrated with Fleet Control for centralized management of multiple printers.",
    price: "R88 695",
    images: [`${IMG}/Form-Auto.png`],
    specs: {
      buildVolume: "Compatible with Form 3+/3B+ build platforms",
      connectivity: "Integrated with printer Wi-Fi/Ethernet",
    },
    features: [
      "Automated part removal",
      "24/7 unattended production",
      "Build Platform 2 compatible",
      "Fleet Control integration",
      "Print queue management",
      "Robotic arm system",
      "Increases throughput 2-4x",
      "Remote monitoring via Dashboard",
      "Hands-free operation",
    ],
  },
  {
    id: "formlabs-form-wash",
    name: "Form Wash",
    brand: "Formlabs",
    slug: "formlabs-form-wash",
    description: "Form Wash automates the critical washing step in resin 3D printing, delivering consistent, repeatable results every time. The agitation system thoroughly cleans parts in IPA (isopropyl alcohol), removing uncured resin from surfaces and internal channels. Programmable wash cycles and a magnetic drive ensure optimal cleaning without manual scrubbing.",
    price: "R16 959",
    images: [`${IMG}/Form-Wash.png`],
    specs: {
      buildVolume: "Fits Form 3/3+/3B+ build platforms",
      materials: "IPA (isopropyl alcohol) solvent",
      connectivity: "Standalone operation",
    },
    features: [
      "Automated IPA washing",
      "Programmable wash cycles (10-20 min)",
      "Magnetic impeller agitation",
      "Consistent, repeatable results",
      "Basket fits Form 3 build platform",
      "Solvent-resistant construction",
      "Easy solvent replacement",
      "Reduces manual post-processing",
    ],
  },
  {
    id: "formlabs-form-wash-l",
    name: "Form Wash L",
    brand: "Formlabs",
    slug: "formlabs-form-wash-l",
    description: "Form Wash L is the large-format washing solution designed specifically for Form 3L and Form 4L prints. With a 36-liter solvent capacity, it handles the largest builds while maintaining the same consistent, automated washing quality as the standard Form Wash. Essential for large-format resin printing workflows.",
    price: "R99 000",
    images: [`${IMG}/Form-Wash-L.png`],
    specs: {
      buildVolume: "Fits Form 3L/4L build platforms (335 x 200 mm)",
      materials: "IPA (isopropyl alcohol) - 36L capacity",
      connectivity: "Standalone operation",
    },
    features: [
      "Large-format washing (36L capacity)",
      "Form 3L/4L build platform compatible",
      "Automated agitation system",
      "Programmable wash cycles",
      "Batch processing capability",
      "Industrial-grade construction",
      "Easy solvent management",
      "Consistent large-part cleaning",
    ],
  },
  {
    id: "formlabs-form-cure-l",
    name: "Form Cure L",
    brand: "Formlabs",
    slug: "formlabs-form-cure-l",
    description: "Form Cure L provides uniform UV post-curing for large-format resin prints from the Form 3L and Form 4L. With 360° UV exposure and precise temperature control up to 80°C, it ensures optimal mechanical properties for engineering and production parts. Material-specific presets automate the curing process for consistent results.",
    price: "R108 999",
    images: [`${IMG}/Form-Cure-L.png`],
    specs: {
      buildVolume: "Fits Form 3L/4L build platforms (335 x 200 x 300 mm)",
      materials: "All Formlabs resins",
      connectivity: "Standalone operation",
      nozzleTemp: "Temperature control up to 80°C",
    },
    features: [
      "Large-format UV curing chamber",
      "360° uniform UV exposure",
      "Temperature control up to 80°C",
      "Material-specific presets",
      "Rotating turntable",
      "13 high-power UV LEDs",
      "Form 3L/4L compatible",
      "Optimizes mechanical properties",
    ],
  },
  {
    id: "formlabs-form-wash-gen2",
    name: "Form Wash Gen 2",
    brand: "Formlabs",
    slug: "formlabs-form-wash-gen2",
    description: "Form Wash Gen 2 is the second-generation automated washing station with improved efficiency and user experience. Featuring faster wash cycles, enhanced agitation, and a refined interface, it delivers cleaner parts with less solvent consumption. Compatible with Form 3, Form 3+, Form 3B+, and Form 4 printers.",
    price: "R17 999",
    images: [`${IMG}/Form-Wash-Gen-2.png`],
    specs: {
      buildVolume: "Fits Form 3/3+/3B+/4 build platforms",
      materials: "IPA (isopropyl alcohol) solvent",
      connectivity: "Standalone operation",
    },
    features: [
      "Gen 2 enhanced agitation system",
      "Faster wash cycles",
      "Improved solvent efficiency",
      "Refined user interface",
      "Form 4 compatible",
      "Magnetic impeller drive",
      "Programmable cycle times",
      "Reduced solvent consumption",
    ],
  },
  {
    id: "formlabs-fuse-1-plus",
    name: "Fuse 1+",
    brand: "Formlabs",
    slug: "formlabs-fuse-1-plus",
    description: "The Fuse 1+ is Formlabs' industrial-grade Selective Laser Sintering (SLS) 3D printer, bringing production-quality nylon parts to the desktop. With self-supporting powder bed technology, it prints complex geometries without supports, enabling designs impossible with other technologies. The 30W laser delivers faster print speeds and improved surface finish for functional prototypes and end-use parts.",
    price: "From R727 000",
    images: [`${IMG}/Fuse-1+.png`],
    specs: {
      buildVolume: "165 x 165 x 300 mm (8.1L)",
      resolution: "110 micron (layer height)",
      materials: "Nylon 12, Nylon 11, Nylon 12 GF, Nylon 11 CF, TPU 90A",
      connectivity: "Wi-Fi (2.4GHz/5GHz), Ethernet",
      printSpeed: "30W laser for faster sintering",
    },
    features: [
      "Selective Laser Sintering (SLS)",
      "30W industrial laser",
      "Self-supporting powder bed",
      "No support structures needed",
      "High-performance nylon materials",
      "Carbon fiber and glass-filled options",
      "Fuse Sift powder recovery system",
      "Surface Armor for improved finish",
      "Production-ready part quality",
    ],
  },

  // ==================== BAMBU LAB ====================
  {
    id: "bambu-lab-a1-mini",
    name: "A1 Mini",
    brand: "Bambu Lab",
    slug: "bambu-lab-a1-mini",
    description: "The Bambu Lab A1 Mini is a compact, beginner-friendly 3D printer that delivers exceptional print quality without complexity. Featuring fully automatic calibration, vibration compensation, and flow calibration, it produces professional results right out of the box. The integrated camera enables AI-powered spaghetti detection and remote monitoring via the Bambu Handy app.",
    price: "R6 295",
    images: [`${IMG}/A1-Mini.png`],
    specs: {
      buildVolume: "180 x 180 x 180 mm",
      resolution: "50 - 500 micron (layer height)",
      materials: "PLA, PETG, TPU, PVA, PLA-CF",
      connectivity: "Wi-Fi (2.4GHz)",
      printSpeed: "Up to 500 mm/s (max acceleration 10,000 mm/s²)",
      nozzleTemp: "Up to 300°C",
      bedTemp: "Up to 80°C (textured PEI plate)",
    },
    features: [
      "Fully automatic calibration",
      "Vibration compensation (input shaping)",
      "Flow rate calibration",
      "AI-powered spaghetti detection",
      "Integrated camera for monitoring",
      "Bambu Studio & Handy app",
      "Quick-swap nozzle system",
      "Textured PEI build plate",
      "AMS Lite compatible (4-color)",
    ],
  },
  {
    id: "bambu-lab-a1-mini-combo",
    name: "A1 Mini Combo",
    brand: "Bambu Lab",
    slug: "bambu-lab-a1-mini-combo",
    description: "The A1 Mini Combo bundles the compact A1 Mini printer with the AMS Lite multi-material system, enabling seamless 4-color printing. The AMS Lite features RFID filament recognition for automatic material profile loading, making multi-color prints as simple as single-color. Perfect for creative projects, educational settings, and hobbyists wanting vibrant multi-color capabilities.",
    price: "R10 899",
    images: [`${IMG}/A1-Mini-Combo.png`],
    specs: {
      buildVolume: "180 x 180 x 180 mm",
      resolution: "50 - 500 micron (layer height)",
      materials: "PLA, PETG, TPU, PVA, PLA-CF (4 colors simultaneously)",
      connectivity: "Wi-Fi (2.4GHz)",
      printSpeed: "Up to 500 mm/s (max acceleration 10,000 mm/s²)",
      nozzleTemp: "Up to 300°C",
      bedTemp: "Up to 80°C (textured PEI plate)",
    },
    features: [
      "AMS Lite included (4-spool capacity)",
      "4-color/multi-material printing",
      "RFID filament recognition",
      "Automatic material profile loading",
      "Fully automatic calibration",
      "AI spaghetti detection",
      "Bambu Studio color painting",
      "Seamless filament switching",
      "Remote monitoring via app",
    ],
  },
  {
    id: "bambu-lab-a1",
    name: "A1",
    brand: "Bambu Lab",
    slug: "bambu-lab-a1",
    description: "The Bambu Lab A1 is a full-size bedslinger printer offering a generous 256 x 256 x 256 mm build volume with the same exceptional quality and ease-of-use as the A1 Mini. Featuring automatic calibration, vibration compensation, and flow calibration, it delivers consistent, high-quality prints for larger projects. The open design provides easy access while maintaining excellent print quality.",
    price: "R9 299",
    images: [`${IMG}/A1.png`],
    specs: {
      buildVolume: "256 x 256 x 256 mm",
      resolution: "50 - 500 micron (layer height)",
      materials: "PLA, PETG, TPU, PVA, PLA-CF",
      connectivity: "Wi-Fi (2.4GHz)",
      printSpeed: "Up to 500 mm/s (max acceleration 10,000 mm/s²)",
      nozzleTemp: "Up to 300°C",
      bedTemp: "Up to 100°C (textured PEI plate)",
    },
    features: [
      "Large 256mm³ build volume",
      "Fully automatic calibration",
      "Vibration compensation (input shaping)",
      "Flow rate calibration",
      "AI spaghetti detection",
      "Integrated camera monitoring",
      "Quick-swap nozzle system",
      "AMS Lite compatible (4-color)",
      "Bambu Studio & Handy app",
    ],
  },
  {
    id: "bambu-lab-a1-combo",
    name: "A1 Combo",
    brand: "Bambu Lab",
    slug: "bambu-lab-a1-combo",
    description: "The A1 Combo combines the full-size A1 printer with the AMS Lite system for large-format multi-color printing. With a 256 x 256 x 256 mm build volume and 4-color capability, it's ideal for creating impressive multi-color models, functional prototypes, and creative projects at scale. RFID filament recognition ensures optimal settings for every material.",
    price: "R13 499",
    images: [`${IMG}/A1-Combo.png`],
    specs: {
      buildVolume: "256 x 256 x 256 mm",
      resolution: "50 - 500 micron (layer height)",
      materials: "PLA, PETG, TPU, PVA, PLA-CF (4 colors simultaneously)",
      connectivity: "Wi-Fi (2.4GHz)",
      printSpeed: "Up to 500 mm/s (max acceleration 10,000 mm/s²)",
      nozzleTemp: "Up to 300°C",
      bedTemp: "Up to 100°C (textured PEI plate)",
    },
    features: [
      "AMS Lite included (4-spool capacity)",
      "Large 256mm³ build volume",
      "4-color/multi-material printing",
      "RFID filament recognition",
      "Fully automatic calibration",
      "AI spaghetti detection",
      "Bambu Studio color painting",
      "Seamless filament switching",
      "Remote monitoring via app",
    ],
  },
  {
    id: "bambu-lab-p1p",
    name: "Bambu Lab P1P",
    brand: "Bambu Lab",
    slug: "bambu-lab-p1p",
    description: "The Bambu Lab P1P is a high-speed CoreXY 3D printer with an open frame design, delivering professional-grade speed and reliability at an accessible price. With 500 mm/s print speeds and 20,000 mm/s² acceleration, it dramatically reduces print times while maintaining quality. The open design provides easy access and is ideal for PLA and PETG printing.",
    price: "R14 499",
    images: [`${IMG}/Bambu-Lab-P1P.png`],
    specs: {
      buildVolume: "256 x 256 x 256 mm",
      resolution: "50 - 500 micron (layer height)",
      materials: "PLA, PETG, TPU, PLA-CF, PETG-CF",
      connectivity: "Wi-Fi (2.4GHz/5GHz), LAN",
      printSpeed: "Up to 500 mm/s (max acceleration 20,000 mm/s²)",
      nozzleTemp: "Up to 300°C",
      bedTemp: "Up to 100°C (textured PEI plate)",
    },
    features: [
      "CoreXY motion system",
      "20,000 mm/s² acceleration",
      "Open frame design",
      "Dual-gear direct drive extruder",
      "Automatic calibration",
      "Vibration compensation",
      "AMS compatible (up to 16 colors)",
      "Bambu Studio & Handy app",
      "Upgradeable to enclosed",
    ],
  },
  {
    id: "bambu-lab-p1s",
    name: "Bambu Lab P1S",
    brand: "Bambu Lab",
    slug: "bambu-lab-p1s",
    description: "The Bambu Lab P1S is a fully enclosed CoreXY 3D printer designed for advanced filaments like ABS, ASA, and PA. The enclosed chamber maintains stable temperatures while the activated carbon filter reduces odors and captures particles. With the same high-speed performance as the P1P plus enhanced cooling, it's the ideal choice for engineering materials.",
    price: "R14 999",
    images: [`${IMG}/Bambu-Lab-P1S.png`],
    specs: {
      buildVolume: "256 x 256 x 256 mm",
      resolution: "50 - 500 micron (layer height)",
      materials: "PLA, PETG, TPU, PVA, ABS, ASA, PA, PC, PET-CF, PA-CF",
      connectivity: "Wi-Fi (2.4GHz/5GHz), LAN",
      printSpeed: "Up to 500 mm/s (max acceleration 20,000 mm/s²)",
      nozzleTemp: "Up to 300°C",
      bedTemp: "Up to 110°C (heated chamber)",
    },
    features: [
      "Fully enclosed chamber",
      "Activated carbon air filter",
      "Enhanced auxiliary cooling",
      "CoreXY motion (20,000 mm/s²)",
      "Engineering material support",
      "Hardened steel nozzle option",
      "AMS compatible (up to 16 colors)",
      "Integrated camera monitoring",
      "Bambu Studio & Handy app",
    ],
  },
  {
    id: "bambu-lab-p1s-ams-combo",
    name: "Bambu Lab P1S & AMS Combo",
    brand: "Bambu Lab",
    slug: "bambu-lab-p1s-ams-combo",
    description: "The P1S & AMS Combo bundles the enclosed P1S printer with the Automatic Material System for professional multi-color and multi-material printing. The AMS enables up to 4 colors per unit (16 colors with 4 AMS units), with automatic filament switching and humidity-controlled storage. Perfect for complex multi-material engineering parts and vibrant multi-color prints.",
    price: "R21 995",
    images: [`${IMG}/Bambu-Lab-P1S-and-AMS-Combo.png`],
    specs: {
      buildVolume: "256 x 256 x 256 mm",
      resolution: "50 - 500 micron (layer height)",
      materials: "PLA, PETG, TPU, PVA, ABS, ASA, PA, PC (4 colors simultaneously)",
      connectivity: "Wi-Fi (2.4GHz/5GHz), LAN",
      printSpeed: "Up to 500 mm/s (max acceleration 20,000 mm/s²)",
      nozzleTemp: "Up to 300°C",
      bedTemp: "Up to 110°C (heated chamber)",
    },
    features: [
      "AMS included (4-spool capacity)",
      "4-color/multi-material printing",
      "RFID filament recognition",
      "Humidity-controlled storage",
      "Fully enclosed chamber",
      "Activated carbon filter",
      "Expandable to 16 colors (4x AMS)",
      "Automatic filament switching",
      "Soluble support materials (PVA)",
    ],
  },
  {
    id: "bambu-lab-p1s-combo-2-pro",
    name: "Bambu Lab P1S Combo 2 Pro",
    brand: "Bambu Lab",
    slug: "bambu-lab-p1s-combo-2-pro",
    description: "The P1S Combo 2 Pro pairs the enclosed P1S printer with the next-generation AMS 2 Pro system featuring enhanced filament handling with a buffer system for smoother material transitions. The AMS 2 Pro reduces failed prints from tangled filament and enables more reliable multi-color printing with challenging materials.",
    price: "R23 999",
    images: [`${IMG}/P1S-Combo-2-Pro-with-Buffer.jpg`],
    specs: {
      buildVolume: "256 x 256 x 256 mm",
      resolution: "50 - 500 micron (layer height)",
      materials: "PLA, PETG, TPU, PVA, ABS, ASA, PA, PC (4 colors simultaneously)",
      connectivity: "Wi-Fi (2.4GHz/5GHz), LAN",
      printSpeed: "Up to 500 mm/s (max acceleration 20,000 mm/s²)",
      nozzleTemp: "Up to 300°C",
      bedTemp: "Up to 110°C (heated chamber)",
    },
    features: [
      "AMS 2 Pro with buffer system",
      "Enhanced filament path reliability",
      "Reduced tangling and jams",
      "Fully enclosed chamber",
      "Activated carbon filter",
      "RFID filament recognition",
      "Humidity-controlled storage",
      "Expandable to 16 colors",
      "Improved multi-material transitions",
    ],
  },
  {
    id: "bambu-lab-p2s",
    name: "Bambu Lab P2S",
    brand: "Bambu Lab",
    slug: "bambu-lab-p2s",
    description: "Fully enclosed CoreXY 3D printer with an adaptive airflow system that can draw in external air for low-temperature filaments and switch to internal circulation with filtration for higher-temperature printing. Includes a touchscreen and a 1080p live view camera.",
    price: "R17 695",
    images: [`${IMG}/Bambu-Lab-P2S.png`],
    specs: {
      buildVolume: "256 x 256 x 256 mm",
      resolution: "50 - 500 micron",
      materials: "PLA, PETG, ABS, ASA, PA, PC",
      connectivity: "Wi-Fi (2.4G & 5G)",
      printSpeed: "Max toolhead speed: 600 mm/s",
      nozzleTemp: "Max nozzle temperature: 300°C",
      bedTemp: "Max heatbed temperature: 110°C",
    },
    features: [
      "Adaptive airflow system",
      "Internal circulation filtration",
      "Touchscreen",
      "1080p live view camera (30fps)",
      "Max acceleration: 20,000 mm/s²",
    ],
  },
  {
    id: "bambu-lab-p2s-combo",
    name: "Bambu Lab P2S Combo",
    brand: "Bambu Lab",
    slug: "bambu-lab-p2s-combo",
    description: "The P2S Combo bundles the advanced P2S printer with the AMS for seamless multi-color and multi-material printing. Combining the P2S's adaptive airflow, 600 mm/s speeds, and 1080p camera with 4-color capability, it's the complete solution for professional multi-color workflows.",
    price: "R25 445",
    images: [`${IMG}/Bambu-Lab-P2S-Combo.png`],
    specs: {
      buildVolume: "256 x 256 x 256 mm",
      resolution: "50 - 500 micron (layer height)",
      materials: "PLA, PETG, TPU, PVA, ABS, ASA, PA, PC (4 colors simultaneously)",
      connectivity: "Wi-Fi (2.4GHz/5GHz), LAN",
      printSpeed: "Up to 600 mm/s (max acceleration 20,000 mm/s²)",
      nozzleTemp: "Up to 300°C",
      bedTemp: "Up to 110°C (heated chamber)",
    },
    features: [
      "AMS included (4-spool capacity)",
      "Adaptive airflow system",
      "4-color/multi-material printing",
      "1080p camera (30fps)",
      "Touchscreen interface",
      "RFID filament recognition",
      "70% more extrusion force",
      "Flow-rate compensation",
      "Expandable to 16 colors",
    ],
  },
  {
    id: "bambu-lab-x1-carbon",
    name: "Bambu Lab X1 Carbon",
    brand: "Bambu Lab",
    slug: "bambu-lab-x1-carbon",
    description: "The Bambu Lab X1 Carbon is the flagship CoreXY 3D printer featuring Lidar-based first layer scanning, AI-powered failure detection, and a hardened steel nozzle for carbon fiber and abrasive materials. With 500 mm/s speeds, 20,000 mm/s² acceleration, and a fully enclosed heated chamber, it delivers professional results with engineering-grade materials.",
    price: "R32 999",
    images: [`${IMG}/Bambu-Lab-X1-Carbon-Printer.png`],
    specs: {
      buildVolume: "256 x 256 x 256 mm",
      resolution: "50 - 500 micron (layer height)",
      materials: "PLA, PETG, TPU, PVA, ABS, ASA, PA, PC, PA-CF, PET-CF",
      connectivity: "Wi-Fi (2.4GHz/5GHz), LAN",
      printSpeed: "Up to 500 mm/s (max acceleration 20,000 mm/s²)",
      nozzleTemp: "Up to 300°C",
      bedTemp: "Up to 110°C (heated chamber up to 60°C)",
    },
    features: [
      "Lidar first layer scanning",
      "AI-powered failure detection",
      "Hardened steel nozzle included",
      "Carbon fiber material support",
      "Fully enclosed heated chamber",
      "Dual-gear direct drive extruder",
      "7\" touchscreen display",
      "AMS compatible (up to 16 colors)",
      "Micro Lidar for flow calibration",
    ],
  },
  {
    id: "bambu-lab-x1-carbon-ams-combo",
    name: "Bambu Lab X1 Carbon & AMS Combo",
    brand: "Bambu Lab",
    slug: "bambu-lab-x1-carbon-ams-combo",
    description: "The X1 Carbon & AMS Combo combines Bambu Lab's flagship printer with the Automatic Material System for professional multi-color and multi-material printing. With Lidar scanning, AI failure detection, and 4-color capability (expandable to 16), it's the ultimate solution for complex engineering parts and stunning multi-color prints.",
    price: "R39 999",
    images: [`${IMG}/Bambu-Lab-X1-Carbon-and-AMS-Combo.png`],
    specs: {
      buildVolume: "256 x 256 x 256 mm",
      resolution: "50 - 500 micron (layer height)",
      materials: "PLA, PETG, TPU, PVA, ABS, ASA, PA, PC, PA-CF, PET-CF (4 colors simultaneously)",
      connectivity: "Wi-Fi (2.4GHz/5GHz), LAN",
      printSpeed: "Up to 500 mm/s (max acceleration 20,000 mm/s²)",
      nozzleTemp: "Up to 300°C",
      bedTemp: "Up to 110°C (heated chamber up to 60°C)",
    },
    features: [
      "AMS included (4-spool capacity)",
      "Lidar first layer scanning",
      "AI-powered failure detection",
      "4-color/multi-material printing",
      "Expandable to 16 colors (4x AMS)",
      "Hardened steel nozzle",
      "RFID filament recognition",
      "Soluble support materials (PVA)",
      "Humidity-controlled storage",
    ],
  },
  {
    id: "bambu-lab-x1-carbon-combo-2-pro",
    name: "Bambu Lab X1 Carbon Combo 2 Pro",
    brand: "Bambu Lab",
    slug: "bambu-lab-x1-carbon-combo-2-pro",
    description: "The X1 Carbon Combo 2 Pro pairs the flagship X1 Carbon with the next-generation AMS 2 Pro featuring an integrated buffer system for smoother filament transitions and reduced failures. This premium combo delivers the most reliable multi-material printing experience for demanding professional applications.",
    price: "R44 707",
    images: [`${IMG}/Bambu-Lab-X1-Carbon-Combo-2-Pro.png`],
    specs: {
      buildVolume: "256 x 256 x 256 mm",
      resolution: "50 - 500 micron (layer height)",
      materials: "PLA, PETG, TPU, PVA, ABS, ASA, PA, PC, PA-CF, PET-CF (4 colors simultaneously)",
      connectivity: "Wi-Fi (2.4GHz/5GHz), LAN",
      printSpeed: "Up to 500 mm/s (max acceleration 20,000 mm/s²)",
      nozzleTemp: "Up to 300°C",
      bedTemp: "Up to 110°C (heated chamber up to 60°C)",
    },
    features: [
      "AMS 2 Pro with buffer system",
      "Enhanced filament path reliability",
      "Lidar first layer scanning",
      "AI-powered failure detection",
      "Reduced tangling and jams",
      "Hardened steel nozzle",
      "Expandable to 16 colors",
      "Premium multi-material experience",
      "Professional-grade reliability",
    ],
  },
  {
    id: "bambu-lab-x1e-ams-combo",
    name: "Bambu Lab X1E & AMS Combo",
    brand: "Bambu Lab",
    slug: "bambu-lab-x1e-ams-combo",
    description: "The Bambu Lab X1E is the enterprise-grade 3D printer designed for industrial environments requiring enhanced security, reliability, and high-temperature material capability. With offline mode for air-gapped networks, hardened components for abrasive materials, and chamber temperatures up to 60°C, it handles demanding engineering materials like PA-CF, PAHT-CF, and PPS-CF.",
    price: "R65 995",
    images: [`${IMG}/Bambu-Lab-X1E-and-AMS-Combo.png`],
    specs: {
      buildVolume: "256 x 256 x 256 mm",
      resolution: "50 - 500 micron (layer height)",
      materials: "PA-CF, PAHT-CF, PPS-CF, PPA-CF, PET-CF, engineering-grade composites",
      connectivity: "Wi-Fi (2.4GHz/5GHz), LAN, Offline/Air-gapped mode",
      printSpeed: "Up to 500 mm/s (max acceleration 20,000 mm/s²)",
      nozzleTemp: "Up to 320°C (high-temp hot end)",
      bedTemp: "Up to 120°C (heated chamber up to 60°C)",
    },
    features: [
      "Enterprise security features",
      "Offline/air-gapped operation",
      "Hardened steel components",
      "High-temperature materials (320°C)",
      "AMS included (4-spool capacity)",
      "Lidar first layer scanning",
      "AI failure detection",
      "Industrial-grade reliability",
      "Data security compliance",
    ],
  },
  {
    id: "bambu-lab-h2c-combo",
    name: "Bambu Lab H2C Combo",
    brand: "Bambu Lab",
    slug: "bambu-lab-h2c-combo",
    description: "Dual-hotend CoreXY system designed for multi-material workflows, with induction hotend rack support and compatibility with laser and cutting modules depending on configuration.",
    price: "R45 999",
    images: [`${IMG}/Bambu-Lab-H2C-Combo.png`],
    specs: {
      buildVolume: "325 x 320 x 325 mm",
      materials: "PLA, PETG, TPU, PVA, BVOH, ABS, ASA, PC, PA, PET, PPS (and fiber-reinforced variants)",
      connectivity: "Wi-Fi, LAN",
      nozzleTemp: "Max nozzle temperature: 350°C",
      bedTemp: "Max heatbed temperature: 120°C",
    },
    features: [
      "Dual-hotend CoreXY",
      "Laser/cutting ecosystem compatibility",
      "Max chamber temperature: 65°C",
      "H2 series universal hotends (standard/high-flow/tungsten carbide options)",
    ],
  },
  {
    id: "bambu-lab-h2c-laser-10w",
    name: "Bambu Lab H2C Laser 10W",
    brand: "Bambu Lab",
    slug: "bambu-lab-h2c-laser-10w",
    description: "Hybrid system with 10W laser engraving capability.",
    price: "R52 999",
    images: [`${IMG}/Bambu-Lab-H2C-Laser-10W.png`],
    specs: {
      buildVolume: "Large format hybrid",
      materials: "Multiple material types",
      connectivity: "Wi-Fi, LAN",
    },
    features: ["10W laser", "3D printing", "Laser engraving", "Multi-function"],
  },
  {
    id: "bambu-lab-h2d",
    name: "Bambu Lab H2D",
    brand: "Bambu Lab",
    slug: "bambu-lab-h2d",
    description: "Dual-hotend CoreXY platform designed for multi-material printing with an optional laser ecosystem (depending on version). Uses H2-series hotends and supports automated filament cutting/switching workflows.",
    price: "R53 499",
    images: [`${IMG}/Bambu-Lab-H2D.png`],
    specs: {
      buildVolume: "325 x 320 x 325 mm",
      resolution: "50 - 500 micron",
      materials: "PLA, PETG, TPU, PVA, BVOH, ABS, ASA, PC, PA, PET, PPS (and fiber-reinforced variants)",
      connectivity: "Wi-Fi, LAN",
      nozzleTemp: "Max nozzle temperature: 350°C",
      bedTemp: "Max heatbed temperature: 120°C",
    },
    features: [
      "Dual hotends (interchangeable left/right)",
      "Automated filament cutting and switching",
      "Laser ecosystem support (by configuration)",
    ],
  },
  {
    id: "bambu-lab-h2d-ams-combo",
    name: "Bambu Lab H2D AMS Combo",
    brand: "Bambu Lab",
    slug: "bambu-lab-h2d-ams-combo",
    description: "H2D with AMS for multi-color 3D printing capabilities.",
    price: "R62 865",
    images: [`${IMG}/Bambu-Lab-H2D-AMS-Combo.png`],
    specs: {
      buildVolume: "Large format hybrid",
      materials: "Multiple material types",
      connectivity: "Wi-Fi, LAN",
    },
    features: ["AMS included", "3D printing", "CNC milling", "Laser engraving"],
  },
  {
    id: "bambu-lab-h2d-laser-10w",
    name: "Bambu Lab H2D Laser Full Combo 10W",
    brand: "Bambu Lab",
    slug: "bambu-lab-h2d-laser-10w",
    description: "H2D with 10W laser for engraving and cutting.",
    price: "R74 999",
    images: [`${IMG}/Bambu-Lab-H2D-Laser-Full-Combo-10-W.png`],
    specs: {
      buildVolume: "Large format hybrid",
      materials: "Multiple material types",
      connectivity: "Wi-Fi, LAN",
    },
    features: ["10W laser", "3D printing", "CNC milling", "Full combo"],
  },
  {
    id: "bambu-lab-h2d-laser-40w",
    name: "Bambu Lab H2D Laser Full Combo 40W",
    brand: "Bambu Lab",
    slug: "bambu-lab-h2d-laser-40w",
    description: "H2D with powerful 40W laser for heavy-duty engraving and cutting.",
    price: "R94 098",
    images: [`${IMG}/Bambu-Lab-H2D-Laser-Full-Combo-40-W.png`],
    specs: {
      buildVolume: "Large format hybrid",
      materials: "Multiple material types",
      connectivity: "Wi-Fi, LAN",
    },
    features: ["40W laser", "3D printing", "CNC milling", "Heavy-duty cutting"],
  },

  // ==================== CREALITY ====================
  {
    id: "creality-k1",
    name: "Creality K1",
    brand: "Creality",
    slug: "creality-k1",
    description: "High-speed CoreXY 3D printer with speeds up to 600mm/s and enclosed design.",
    price: "R11 699",
    images: [`${IMG}/Creality-K1.png`],
    specs: {
      buildVolume: "220 x 220 x 250 mm",
      resolution: "50 - 500 micron",
      materials: "PLA, PETG, ABS, ASA, TPU",
      connectivity: "Wi-Fi, LAN",
      printSpeed: "Up to 600 mm/s",
      nozzleTemp: "Up to 300°C",
      bedTemp: "Up to 100°C",
    },
    features: ["CoreXY motion", "Enclosed chamber", "Auto calibration", "AI camera"],
  },
  {
    id: "creality-k1-max",
    name: "Creality K1 MAX",
    brand: "Creality",
    slug: "creality-k1-max",
    description: "Large-format high-speed CoreXY printer with AI camera for monitoring.",
    price: "R14 999",
    images: [`${IMG}/Creality-K1-MAX.png`],
    specs: {
      buildVolume: "300 x 300 x 300 mm",
      resolution: "50 - 500 micron",
      materials: "PLA, PETG, ABS, ASA, TPU",
      connectivity: "Wi-Fi, LAN",
      printSpeed: "Up to 600 mm/s",
      nozzleTemp: "Up to 300°C",
      bedTemp: "Up to 100°C",
    },
    features: ["Large format", "AI camera", "CoreXY motion", "Auto calibration"],
  },
  {
    id: "creality-k1c",
    name: "Creality K1C",
    brand: "Creality",
    slug: "creality-k1c",
    description: "Carbon fiber optimized high-speed printer with hardened nozzle.",
    price: "R12 999",
    images: [`${IMG}/Creality-K1C.png`],
    specs: {
      buildVolume: "220 x 220 x 250 mm",
      resolution: "50 - 500 micron",
      materials: "PLA, PETG, ABS, ASA, Carbon Fiber, TPU",
      connectivity: "Wi-Fi, LAN",
      printSpeed: "Up to 600 mm/s",
      nozzleTemp: "Up to 300°C",
    },
    features: ["Hardened nozzle", "Carbon fiber capable", "Enhanced cooling", "CoreXY motion"],
  },
  {
    id: "creality-k1-se",
    name: "Creality K1 SE",
    brand: "Creality",
    slug: "creality-k1-se",
    description: "Special edition K1 with enhanced features and reliability.",
    price: "R10 999",
    images: [`${IMG}/Creality-K1-SE.png`],
    specs: {
      buildVolume: "220 x 220 x 250 mm",
      resolution: "50 - 500 micron",
      materials: "PLA, PETG, ABS, TPU",
      connectivity: "Wi-Fi, LAN",
      printSpeed: "Up to 600 mm/s",
      nozzleTemp: "Up to 300°C",
    },
    features: ["Special edition", "CoreXY motion", "Enclosed chamber", "Auto calibration"],
  },
  {
    id: "creality-k2-plus",
    name: "Creality K2 Plus",
    brand: "Creality",
    slug: "creality-k2-plus",
    description: "Next-generation large-format CoreXY printer with advanced features.",
    price: "R24 999",
    images: [`${IMG}/Creality-K2-Plus.png`],
    specs: {
      buildVolume: "350 x 350 x 350 mm",
      resolution: "50 - 500 micron",
      materials: "PLA, PETG, ABS, ASA, PA, PC",
      connectivity: "Wi-Fi, LAN",
      printSpeed: "Up to 600 mm/s",
      nozzleTemp: "Up to 300°C",
      bedTemp: "Up to 110°C",
    },
    features: ["Large format", "Next-gen CoreXY", "Advanced features", "Multi-material ready"],
  },
  {
    id: "creality-k2-plus-combo",
    name: "Creality K2 Plus Combo",
    brand: "Creality",
    slug: "creality-k2-plus-combo",
    description: "K2 Plus with multi-material system for multi-color printing.",
    price: "R33 599",
    images: [`${IMG}/Creality-K2-Plus-Combo.png`],
    specs: {
      buildVolume: "350 x 350 x 350 mm",
      resolution: "50 - 500 micron",
      materials: "PLA, PETG, ABS, ASA, PA, PC",
      connectivity: "Wi-Fi, LAN",
      printSpeed: "Up to 600 mm/s",
      nozzleTemp: "Up to 300°C",
      bedTemp: "Up to 110°C",
    },
    features: ["Multi-material system", "Large format", "Multi-color printing", "Advanced features"],
  },
  {
    id: "creality-k2-pro-combo",
    name: "Creality K2 Pro Combo",
    brand: "Creality",
    slug: "creality-k2-pro-combo",
    description: "Professional K2 variant with enhanced capabilities and multi-material system.",
    price: "R29 999",
    images: [`${IMG}/Creality-K2-Pro-Combo.png`],
    specs: {
      buildVolume: "300 x 300 x 300 mm",
      resolution: "50 - 500 micron",
      materials: "PLA, PETG, ABS, ASA, PA, PC",
      connectivity: "Wi-Fi, LAN",
      printSpeed: "Up to 600 mm/s",
      nozzleTemp: "Up to 300°C",
      bedTemp: "Up to 110°C",
    },
    features: ["Pro variant", "Multi-material system", "Enhanced capabilities", "Professional grade"],
  },
  {
    id: "creality-ender-7",
    name: "Creality Ender 7",
    brand: "Creality",
    slug: "creality-ender-7",
    description: "High-speed FDM printer with CoreXY motion system.",
    price: "R8 189",
    images: [`${IMG}/Creality-Ender-7.png`],
    specs: {
      buildVolume: "250 x 250 x 300 mm",
      resolution: "50 - 400 micron",
      materials: "PLA, PETG, ABS, TPU",
      connectivity: "Wi-Fi, USB",
      printSpeed: "Up to 250 mm/s",
      nozzleTemp: "Up to 260°C",
      bedTemp: "Up to 100°C",
    },
    features: ["CoreXY motion", "Linear rails", "Direct drive", "Reliable printing"],
  },
  {
    id: "creality-ender-3-v3-ke",
    name: "Creality Ender 3 V3 KE",
    brand: "Creality",
    slug: "creality-ender-3-v3-ke",
    description: "Klipper-enabled Ender 3 with improved speed and features.",
    price: "R6 999",
    images: [`${IMG}/Creality-Ender-3-V3-KE.png`],
    specs: {
      buildVolume: "220 x 220 x 250 mm",
      resolution: "50 - 400 micron",
      materials: "PLA, PETG, ABS, TPU",
      connectivity: "Wi-Fi, USB",
      printSpeed: "Up to 500 mm/s",
      nozzleTemp: "Up to 260°C",
    },
    features: ["Klipper firmware", "Input shaping", "Auto leveling", "Direct drive"],
  },
  {
    id: "creality-ender-3-v3-plus",
    name: "Creality Ender 3 V3 Plus",
    brand: "Creality",
    slug: "creality-ender-3-v3-plus",
    description: "Larger Ender 3 V3 with expanded build volume.",
    price: "R8 499",
    images: [`${IMG}/Creality-Ender-3-V3-Plus.png`],
    specs: {
      buildVolume: "300 x 300 x 330 mm",
      resolution: "50 - 400 micron",
      materials: "PLA, PETG, ABS, TPU",
      connectivity: "Wi-Fi, USB",
      printSpeed: "Up to 500 mm/s",
      nozzleTemp: "Up to 260°C",
    },
    features: ["Larger build volume", "Klipper firmware", "Input shaping", "Auto leveling"],
  },
  {
    id: "creality-ender-3-s1-plus",
    name: "Creality Ender 3 S1 Plus",
    brand: "Creality",
    slug: "creality-ender-3-s1-plus",
    description: "Enhanced Ender 3 S1 with larger build volume and improved features.",
    price: "R7 999",
    images: [`${IMG}/Creality-Ender-3-S1-Plus.png`],
    specs: {
      buildVolume: "300 x 300 x 300 mm",
      resolution: "50 - 400 micron",
      materials: "PLA, PETG, ABS, TPU",
      connectivity: "Wi-Fi, USB",
      printSpeed: "Up to 150 mm/s",
      nozzleTemp: "Up to 260°C",
    },
    features: ["Larger build volume", "Direct drive", "CR Touch leveling", "Sprite extruder"],
  },
  {
    id: "creality-ender-5-max",
    name: "Creality Ender 5 Max",
    brand: "Creality",
    slug: "creality-ender-5-max",
    description: "Large-format Ender 5 with massive build volume.",
    price: "R12 999",
    images: [`${IMG}/Ender-5-Max.png`],
    specs: {
      buildVolume: "400 x 400 x 400 mm",
      resolution: "50 - 400 micron",
      materials: "PLA, PETG, ABS, TPU",
      connectivity: "USB, SD Card",
      printSpeed: "Up to 180 mm/s",
      nozzleTemp: "Up to 260°C",
    },
    features: ["Massive build volume", "Stable cube frame", "Dual Y-axis", "BL Touch compatible"],
  },
  {
    id: "creality-hi-combo",
    name: "Creality Hi Combo",
    brand: "Creality",
    slug: "creality-hi-combo",
    description: "Creality Hi series with multi-material combo system.",
    price: "R15 999",
    images: [`${IMG}/Creality-Hi-Combo.png`],
    specs: {
      buildVolume: "220 x 220 x 250 mm",
      resolution: "50 - 500 micron",
      materials: "PLA, PETG, ABS, ASA, TPU",
      connectivity: "Wi-Fi, LAN",
      printSpeed: "Up to 600 mm/s",
    },
    features: ["Multi-material system", "High speed", "Auto calibration", "AI monitoring"],
  },

  // ==================== DESKTOP METAL ====================
  {
    id: "desktop-metal-studio-system-plus",
    name: "Desktop Metal Studio System+",
    brand: "Desktop Metal",
    slug: "desktop-metal-studio-system-plus",
    description: "Office-friendly metal 3D printing system for prototyping and low-volume production.",
    price: "Enquire for pricing",
    images: [`${IMG}/Studio-System-+.png`],
    specs: {
      buildVolume: "300 x 200 x 200 mm",
      materials: "17-4 PH, 316L, H13, Copper",
      connectivity: "Ethernet",
    },
    features: ["Bound metal deposition", "Office-friendly", "No loose powder", "Sintering furnace included"],
  },
  {
    id: "desktop-metal-shop-system",
    name: "Desktop Metal Shop System",
    brand: "Desktop Metal",
    slug: "desktop-metal-shop-system",
    description: "High-throughput binder jetting system for metal part production.",
    price: "Enquire for pricing",
    images: [`${IMG}/Shop-System.png`],
    specs: {
      buildVolume: "350 x 220 x 50 mm",
      materials: "17-4 PH, 316L, 4140, Copper",
      connectivity: "Ethernet",
    },
    features: ["Binder jetting", "High throughput", "Production ready", "Multiple materials"],
  },
  {
    id: "desktop-metal-production-system-p1",
    name: "Desktop Metal Production System P-1",
    brand: "Desktop Metal",
    slug: "desktop-metal-production-system-p1",
    description: "Entry-level production binder jetting system for metal parts.",
    price: "Enquire for pricing",
    images: [`${IMG}/Production-System-P-1.png`],
    specs: {
      buildVolume: "200 x 100 x 50 mm",
      materials: "17-4 PH, 316L, 4140",
      connectivity: "Ethernet",
    },
    features: ["Binder jetting", "Production scale", "Entry-level", "Metal parts"],
  },
  {
    id: "desktop-metal-production-system-p50",
    name: "Desktop Metal Production System P-50",
    brand: "Desktop Metal",
    slug: "desktop-metal-production-system-p50",
    description: "High-volume production binder jetting system for industrial metal manufacturing.",
    price: "Enquire for pricing",
    images: [`${IMG}/Production-System-P-50.png`],
    specs: {
      buildVolume: "490 x 380 x 260 mm",
      materials: "17-4 PH, 316L, 4140, Copper",
      connectivity: "Ethernet",
    },
    features: ["High volume", "Industrial scale", "Binder jetting", "Mass production"],
  },

  // ==================== INTAMSYS ====================
  {
    id: "intamsys-funmat-ht",
    name: "Intamsys Funmat HT",
    brand: "Intamsys",
    slug: "intamsys-funmat-ht",
    description: "High-temperature industrial 3D printer for engineering-grade materials.",
    price: "R179 659",
    images: [`${IMG}/Intamsys-Funmat-HT.png`],
    specs: {
      buildVolume: "260 x 260 x 260 mm",
      materials: "PEEK, ULTEM, PPSU, PC, PA",
      connectivity: "Ethernet, USB",
      nozzleTemp: "Up to 450°C",
      bedTemp: "Up to 160°C",
    },
    features: ["High-temp chamber", "PEEK capable", "Industrial grade", "Heated enclosure"],
  },
  {
    id: "intamsys-funmat-pro-410",
    name: "Intamsys Funmat Pro 410",
    brand: "Intamsys",
    slug: "intamsys-funmat-pro-410",
    description: "Professional high-temperature 3D printer for advanced materials.",
    price: "P.O.R",
    images: [`${IMG}/Intamsys-Funmat-Pro-410.png`],
    specs: {
      buildVolume: "305 x 305 x 406 mm",
      materials: "PEEK, ULTEM, PPSU, PC, PA, Carbon Fiber",
      connectivity: "Ethernet, USB",
      nozzleTemp: "Up to 500°C",
      bedTemp: "Up to 160°C",
    },
    features: ["Large format", "500°C nozzle", "Industrial materials", "Dual extrusion"],
  },
  {
    id: "intamsys-funmat-pro-610-ht",
    name: "Intamsys Funmat Pro 610 HT",
    brand: "Intamsys",
    slug: "intamsys-funmat-pro-610-ht",
    description: "Large-format high-temperature industrial 3D printer.",
    price: "P.O.R",
    images: [`${IMG}/Intamsys-Funmat-Pro-610-HT.png`],
    specs: {
      buildVolume: "610 x 508 x 508 mm",
      materials: "PEEK, ULTEM, PPSU, PC, PA, Carbon Fiber",
      connectivity: "Ethernet, USB",
      nozzleTemp: "Up to 500°C",
      bedTemp: "Up to 160°C",
    },
    features: ["Extra large format", "High-temp chamber", "Industrial scale", "Advanced materials"],
  },

  // ==================== BIGREP ====================
  {
    id: "bigrep-one",
    name: "BigRep ONE",
    brand: "BigRep",
    slug: "bigrep-one",
    description: "Large-format industrial 3D printer for full-scale prototypes and end-use parts.",
    price: "P.O.R",
    images: [`${IMG}/BigRep-ONE.png`],
    specs: {
      buildVolume: "1005 x 1005 x 1005 mm",
      materials: "PLA, PETG, ASA, PA, TPU",
      connectivity: "Ethernet",
      printSpeed: "Up to 600 mm/s",
    },
    features: ["1 cubic meter build", "Full-scale prototypes", "Industrial grade", "Dual extrusion"],
  },
  {
    id: "bigrep-pro",
    name: "BigRep PRO",
    brand: "BigRep",
    slug: "bigrep-pro",
    description: "Professional large-format 3D printer with advanced materials capability.",
    price: "P.O.R",
    images: [`${IMG}/BigRep-PRO.2.png`],
    specs: {
      buildVolume: "1005 x 1005 x 1005 mm",
      materials: "Engineering-grade materials, composites",
      connectivity: "Ethernet",
      printSpeed: "Up to 600 mm/s",
    },
    features: ["Professional grade", "Advanced materials", "Large format", "High precision"],
  },
  {
    id: "bigrep-studio",
    name: "BigRep Studio",
    brand: "BigRep",
    slug: "bigrep-studio",
    description: "Compact large-format 3D printer for design studios and workshops.",
    price: "P.O.R",
    images: [`${IMG}/BigRep-Studio.png`],
    specs: {
      buildVolume: "500 x 1000 x 500 mm",
      materials: "PLA, PETG, ASA, PA, TPU",
      connectivity: "Ethernet",
    },
    features: ["Compact large-format", "Studio-friendly", "Dual extrusion", "Enclosed chamber"],
  },

  // ==================== ELEGOO ====================
  {
    id: "elegoo-orangestorm-giga",
    name: "Elegoo OrangeStorm Giga",
    brand: "Elegoo",
    slug: "elegoo-orangestorm-giga",
    description: "Massive industrial-scale FDM 3D printer for large parts and prototypes.",
    price: "Contact for pricing",
    images: [`${IMG}/OrangeStorm-Giga.png`],
    specs: {
      buildVolume: "800 x 800 x 1000 mm",
      materials: "PLA, PETG, ABS, ASA, TPU",
      connectivity: "Wi-Fi, Ethernet",
      printSpeed: "Up to 300 mm/s",
    },
    features: ["Massive build volume", "Industrial scale", "Enclosed chamber", "Multi-zone heating"],
  },
];

export function getPrintersByBrand(brand: Printer["brand"]): Printer[] {
  return printers.filter((p) => p.brand === brand);
}

export function getPrinterBySlug(slug: string): Printer | undefined {
  return printers.find((p) => p.slug === slug || p.id === slug);
}
